Repository codestates/BTAFinalProject-06, pull requests merged in 2022-11, with the labels that each got.

#3 #2 월렛 구조 잡기
  .gitignore
  wallet/.gitignore
  wallet/README.md
  wallet/config/paths.js
  wallet/config/webpack.common.js
  wallet/config/webpack.config.js
  wallet/package-lock.json
  wallet/package.json
  wallet/public/favicon.ico
  wallet/public/icons/icon_128.png
  wallet/public/icons/icon_16.png
  wallet/public/icons/icon_32.png
  wallet/public/icons/icon_48.png
  wallet/public/img/LOGO.png
  wallet/public/img/STX.png
  wallet/public/index.html
  wallet/public/logo192.png
  wallet/public/logo512.png
  wallet/public/manifest.json
  wallet/public/popup.html
  wallet/public/robots.txt
  wallet/src/App.css
  wallet/src/App.js
  wallet/src/App.test.js
  wallet/src/chrome/background.js
  wallet/src/chrome/contentScript.js
  wallet/src/index.css
  wallet/src/index.js
  wallet/src/logo.svg
  wallet/src/pages/Home.js
  wallet/src/pages/Login.js
  wallet/src/reportWebVitals.js
  wallet/src/setupTests.js
  wallet/src/utill/common.js
  wallet/yarn.lock
Labels: feat, high, E:1h, client

#54 [#50]fix: 로그인 키방출 수정, 지갑복구
  wallet/src/api/api.js
  wallet/src/pages/Login.js
  wallet/src/pages/RecoverAccount.js
  wallet/src/pages/Setting.js
Labels: fix, client

#64 [#60] feat: add block & block detail page / account nav connect
  explorer/client/package-lock.json
  explorer/frontend/package-lock.json
  explorer/frontend/src/App.jsx
  explorer/frontend/src/components/RecentBlocks/Block.jsx
  explorer/frontend/src/components/RecentBlocks/RecentBlocks.css
  explorer/frontend/src/components/RecentBlocks/RecentBlocks.jsx
  explorer/frontend/src/components/navbar/Navbar.css
  explorer/frontend/src/components/navbar/Navbar.jsx
  explorer/frontend/src/config.js
  explorer/frontend/src/pages/blockPage/BlockDetailPage.jsx
  explorer/frontend/src/pages/blockPage/BlockMainPage.jsx
  explorer/frontend/src/pages/blockPage/BlockPage.css
  explorer/frontend/src/pages/transactionPage/TransactionMainPage.jsx
  explorer/frontend/src/redux/hederaApi.js
  explorer/frontend/src/redux/netSlice.js
  explorer/frontend/src/utils/getDynamicQuery.js
Labels: client

#70 [#67] feat : 검색 기능 추가
  explorer/frontend/src/components/navbar/Navbar.jsx
  explorer/frontend/src/pages/blockPage/BlockDetailPage.jsx
Labels: feat, client
